### ISSUE TITLE
Pipeline explanation

### ISSUE THREAD

**Issue by hamidb** [griegler/pyfusion#2]
Hello and Thanks for sharing your work. 
Is there any documentation that can be used as the reference for pyfusion?
For instance what is the format of generated tsdf?
Or any pseudo code that can briefly explain what is going on inside fusion_tsdf_cpu() 
Thanks a bunch,
Hamid

**Comment by griegler** [comment]
Unfortunately, there is no proper documentation. For an example how to run the code, you can have a look [here](https://github.com/griegler/octnetfusion/blob/master/src/modelnet/create_data.py).
All the fusion methods work similarly, each voxel is projected into the depth maps. Then, depending on the distance of the voxel center to the image plane (vx_depth) and the depth value in the depth map (on the projected position; dm_depth), a value for the voxel is computed. I hope the rest is understandable from the code.

**Comment by hamidb** [comment]
Thanks a lot. 
Very helpful.
